// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjektLeg;

#nullable disable

namespace ProjektLeg.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20220412083500_NewProperties1")]
    partial class NewProperties1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ProjektLeg.Models.Enemies_killed", b =>
                {
                    b.Property<int>("SaveID")
                        .HasColumnType("int");

                    b.Property<int>("EnemyID")
                        .HasColumnType("int");

                    b.HasKey("SaveID", "EnemyID");

                    b.ToTable("Enemies");
                });

            modelBuilder.Entity("ProjektLeg.Models.Inventory_Items", b =>
                {
                    b.Property<int>("SaveID")
                        .HasColumnType("int");

                    b.Property<int>("ItemID")
                        .HasColumnType("int");

                    b.HasKey("SaveID", "ItemID");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("ProjektLeg.Models.Puzzles", b =>
                {
                    b.Property<int>("Puzzles_ID")
                        .HasColumnType("int");

                    b.Property<int>("Save_ID")
                        .HasColumnType("int");

                    b.HasKey("Puzzles_ID", "Save_ID");

                    b.HasIndex("Save_ID");

                    b.ToTable("Puzzles");
                });

            modelBuilder.Entity("ProjektLeg.Models.Save", b =>
                {
                    b.Property<int>("SaveID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SaveID"), 1L, 1);

                    b.Property<int?>("Armour_ID")
                        .HasColumnType("int");

                    b.Property<long?>("Health")
                        .HasColumnType("bigint");

                    b.Property<int>("RoomID")
                        .HasColumnType("int");

                    b.Property<int?>("Weapon_ID")
                        .HasColumnType("int");

                    b.Property<int>("user_ID")
                        .HasColumnType("int");

                    b.HasKey("SaveID");

                    b.HasIndex("user_ID");

                    b.ToTable("Saves");
                });

            modelBuilder.Entity("ProjektLeg.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("ID");

                    b.HasIndex("Username", "Password");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ProjektLeg.Models.Enemies_killed", b =>
                {
                    b.HasOne("ProjektLeg.Models.Save", "save")
                        .WithMany("Save_Enemies_killed")
                        .HasForeignKey("SaveID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("save");
                });

            modelBuilder.Entity("ProjektLeg.Models.Inventory_Items", b =>
                {
                    b.HasOne("ProjektLeg.Models.Save", "save")
                        .WithMany("Save_Inventory_Items")
                        .HasForeignKey("SaveID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("save");
                });

            modelBuilder.Entity("ProjektLeg.Models.Puzzles", b =>
                {
                    b.HasOne("ProjektLeg.Models.Save", "save")
                        .WithMany("Save_Puzzles")
                        .HasForeignKey("Save_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("save");
                });

            modelBuilder.Entity("ProjektLeg.Models.Save", b =>
                {
                    b.HasOne("ProjektLeg.Models.User", "user")
                        .WithMany("Saves")
                        .HasForeignKey("user_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("ProjektLeg.Models.Save", b =>
                {
                    b.Navigation("Save_Enemies_killed");

                    b.Navigation("Save_Inventory_Items");

                    b.Navigation("Save_Puzzles");
                });

            modelBuilder.Entity("ProjektLeg.Models.User", b =>
                {
                    b.Navigation("Saves");
                });
#pragma warning restore 612, 618
        }
    }
}
