// <auto-generated />
using System;
using Backend_API.db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend_API.Migrations
{
    [DbContext(typeof(DaG_db))]
    [Migration("20220516110238_health")]
    partial class health
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Backend_API.Models.Enemies_killed", b =>
                {
                    b.Property<int>("SaveID")
                        .HasColumnType("int");

                    b.Property<int>("EnemyID")
                        .HasColumnType("int");

                    b.HasKey("SaveID", "EnemyID");

                    b.ToTable("Enemies");
                });

            modelBuilder.Entity("Backend_API.Models.Inventory_Items", b =>
                {
                    b.Property<int>("SaveID")
                        .HasColumnType("int");

                    b.Property<int>("ItemID")
                        .HasColumnType("int");

                    b.HasKey("SaveID", "ItemID");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Backend_API.Models.Puzzles", b =>
                {
                    b.Property<int>("Puzzles_ID")
                        .HasColumnType("int");

                    b.Property<int>("Save_ID")
                        .HasColumnType("int");

                    b.HasKey("Puzzles_ID", "Save_ID");

                    b.HasIndex("Save_ID");

                    b.ToTable("Puzzles");
                });

            modelBuilder.Entity("Backend_API.Models.RoomDescription", b =>
                {
                    b.Property<int>("RoomDescriptionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomDescriptionID"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoomDescriptionID");

                    b.ToTable("RoomDescriptions");

                    b.HasData(
                        new
                        {
                            RoomDescriptionID = 1,
                            Description = "DB says: This is room 1"
                        },
                        new
                        {
                            RoomDescriptionID = 2,
                            Description = "DB says: This is room 2"
                        },
                        new
                        {
                            RoomDescriptionID = 3,
                            Description = "DB says: This is room 3"
                        },
                        new
                        {
                            RoomDescriptionID = 4,
                            Description = "DB says: This is room 4"
                        },
                        new
                        {
                            RoomDescriptionID = 5,
                            Description = "DB says: This is room 5"
                        },
                        new
                        {
                            RoomDescriptionID = 6,
                            Description = "DB says: This is room 6"
                        },
                        new
                        {
                            RoomDescriptionID = 7,
                            Description = "DB says: This is room 7"
                        },
                        new
                        {
                            RoomDescriptionID = 8,
                            Description = "DB says: This is room 8"
                        },
                        new
                        {
                            RoomDescriptionID = 9,
                            Description = "DB says: This is room 9"
                        },
                        new
                        {
                            RoomDescriptionID = 10,
                            Description = "DB says: This is room 10"
                        },
                        new
                        {
                            RoomDescriptionID = 11,
                            Description = "DB says: This is room 11"
                        },
                        new
                        {
                            RoomDescriptionID = 12,
                            Description = "DB says: This is room 12"
                        },
                        new
                        {
                            RoomDescriptionID = 13,
                            Description = "DB says: This is room 13"
                        },
                        new
                        {
                            RoomDescriptionID = 14,
                            Description = "DB says: This is room 14"
                        },
                        new
                        {
                            RoomDescriptionID = 15,
                            Description = "DB says: This is room 15"
                        },
                        new
                        {
                            RoomDescriptionID = 16,
                            Description = "DB says: This is room 16"
                        },
                        new
                        {
                            RoomDescriptionID = 17,
                            Description = "DB says: This is room 17"
                        },
                        new
                        {
                            RoomDescriptionID = 18,
                            Description = "DB says: This is room 18"
                        },
                        new
                        {
                            RoomDescriptionID = 19,
                            Description = "DB says: This is room 19"
                        },
                        new
                        {
                            RoomDescriptionID = 20,
                            Description = "DB says: This is room 20"
                        });
                });

            modelBuilder.Entity("Backend_API.Models.Save", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int?>("Armour_ID")
                        .HasColumnType("int");

                    b.Property<long?>("Health")
                        .HasColumnType("bigint");

                    b.Property<int>("RoomID")
                        .HasColumnType("int");

                    b.Property<string>("SaveName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(64)");

                    b.Property<int?>("Weapon_ID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("Username");

                    b.HasIndex("SaveName", "Username")
                        .IsUnique();

                    b.ToTable("Saves");

                    b.HasData(
                        new
                        {
                            ID = 2,
                            Health = 10L,
                            RoomID = 0,
                            SaveName = "NewGame2",
                            Username = "gamer1"
                        },
                        new
                        {
                            ID = 1,
                            Health = 10L,
                            RoomID = 0,
                            SaveName = "NewGame1",
                            Username = "gamer1"
                        },
                        new
                        {
                            ID = 3,
                            Health = 10L,
                            RoomID = 0,
                            SaveName = "NewGame3",
                            Username = "gamer1"
                        },
                        new
                        {
                            ID = 4,
                            Health = 10L,
                            RoomID = 0,
                            SaveName = "NewGame4",
                            Username = "gamer1"
                        },
                        new
                        {
                            ID = 5,
                            Health = 10L,
                            RoomID = 0,
                            SaveName = "NewGame5",
                            Username = "gamer1"
                        });
                });

            modelBuilder.Entity("Backend_API.Models.User", b =>
                {
                    b.Property<string>("Username")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Username");

                    b.HasIndex("Username", "Password")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Username = "Gamer1",
                            Password = "$2a$11$a0cBl.aqZ0oJ8cM/qM.2euSjSDYdvehOv1BeekubHEg6hA/y0z2mS"
                        });
                });

            modelBuilder.Entity("Backend_API.Models.VisitedRooms", b =>
                {
                    b.Property<int>("SaveId")
                        .HasColumnType("int");

                    b.Property<long>("VistedRoomId")
                        .HasColumnType("bigint");

                    b.HasKey("SaveId", "VistedRoomId");

                    b.ToTable("VisitedRooms");
                });

            modelBuilder.Entity("Backend_API.Models.Enemies_killed", b =>
                {
                    b.HasOne("Backend_API.Models.Save", "save")
                        .WithMany("Save_Enemies_killed")
                        .HasForeignKey("SaveID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("save");
                });

            modelBuilder.Entity("Backend_API.Models.Inventory_Items", b =>
                {
                    b.HasOne("Backend_API.Models.Save", "save")
                        .WithMany("Save_Inventory_Items")
                        .HasForeignKey("SaveID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("save");
                });

            modelBuilder.Entity("Backend_API.Models.Puzzles", b =>
                {
                    b.HasOne("Backend_API.Models.Save", "save")
                        .WithMany("Save_Puzzles")
                        .HasForeignKey("Save_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("save");
                });

            modelBuilder.Entity("Backend_API.Models.Save", b =>
                {
                    b.HasOne("Backend_API.Models.User", "User")
                        .WithMany("Saves")
                        .HasForeignKey("Username")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend_API.Models.VisitedRooms", b =>
                {
                    b.HasOne("Backend_API.Models.Save", "Save")
                        .WithMany("VisitedRooms")
                        .HasForeignKey("SaveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Save");
                });

            modelBuilder.Entity("Backend_API.Models.Save", b =>
                {
                    b.Navigation("Save_Enemies_killed");

                    b.Navigation("Save_Inventory_Items");

                    b.Navigation("Save_Puzzles");

                    b.Navigation("VisitedRooms");
                });

            modelBuilder.Entity("Backend_API.Models.User", b =>
                {
                    b.Navigation("Saves");
                });
#pragma warning restore 612, 618
        }
    }
}
