// <auto-generated />
<<<<<<< HEAD
=======
using System;
>>>>>>> FrontEnd
using Backend_API.db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend_API.Migrations
{
    [DbContext(typeof(DaG_db))]
    partial class DaG_dbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

<<<<<<< HEAD
=======
            modelBuilder.Entity("Backend_API.Models.Enemies_killed", b =>
                {
                    b.Property<int>("SaveID")
                        .HasColumnType("int");

                    b.Property<long>("EnemyID")
                        .HasColumnType("bigint");

                    b.HasKey("SaveID", "EnemyID");

                    b.ToTable("Enemies");
                });

            modelBuilder.Entity("Backend_API.Models.Inventory_Items", b =>
                {
                    b.Property<int>("SaveID")
                        .HasColumnType("int");

                    b.Property<long>("ItemID")
                        .HasColumnType("bigint");

                    b.HasKey("SaveID", "ItemID");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Backend_API.Models.Puzzles", b =>
                {
                    b.Property<int>("Save_ID")
                        .HasColumnType("int");

                    b.Property<long>("Puzzles_ID")
                        .HasColumnType("bigint");

                    b.HasKey("Save_ID", "Puzzles_ID");

                    b.ToTable("Puzzles");
                });

>>>>>>> FrontEnd
            modelBuilder.Entity("Backend_API.Models.RoomDescription", b =>
                {
                    b.Property<int>("RoomDescriptionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomDescriptionID"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoomDescriptionID");

                    b.ToTable("RoomDescriptions");

                    b.HasData(
                        new
                        {
                            RoomDescriptionID = 1,
<<<<<<< HEAD
                            Description = "DB says: This is room 1"
=======
                            Description = "1: The king has died of a magical curse caused by mysterious powers and a dooming presence is in store for the kingdom of Valirea. The threats of raids and magic power from foreign kingdoms are present and will end all of what you love and cherish. A strange oracle has foreseen that all this can be stopped if the Sword of Destiny is found and kept by the kingdom. The Sword of destiny is enchanted with holy powers and can protect the kingdom from evil. But to retrieve The Sword of Destiny, a mighty and brave warrior must face a trial in the lair of doom. It has been told that many have failed and perished in a attempt to retrieve the sword. You see no other choice and volunteer to save the kingdom of Valirea. You have entered the dark lair to retrieve the Sword of Destiny. The sheer cold and silence gives you discomforting feeling. You ask yourself, Is this really a good idea?. To move to the next room, use the arrow - keys or the move - buttons on the screen."
>>>>>>> FrontEnd
                        },
                        new
                        {
                            RoomDescriptionID = 2,
<<<<<<< HEAD
                            Description = "DB says: This is room 2"
=======
                            Description = "2. You hear a strange rumble. What is happening? The opening behind you begins to collapse. You sprint to avoid getting smashed by the falling rocks. There's no escape now! You stumble upon a rusty sword on the ground.Might be useful. Use the interact button to pick up found items. Found items can be located and equipped in the inventory. If you wish to view your character's stats, click the character-option.2"
>>>>>>> FrontEnd
                        },
                        new
                        {
                            RoomDescriptionID = 3,
<<<<<<< HEAD
                            Description = "DB says: This is room 3"
=======
                            Description = "3. That was a strange encounter, but the naked gnoblin is no more. You've made it through to a room with lit torches on the walls. The lit torches reveals blood soaked walls and the thought of you becoming the next victim hits your thoughts.You stumble on a dusty shield in the corner of the room.Might be useful after that encounter."
>>>>>>> FrontEnd
                        },
                        new
                        {
                            RoomDescriptionID = 4,
<<<<<<< HEAD
                            Description = "DB says: This is room 4"
=======
                            Description = "4. The door revealed a tunnel that led to a poorly lit room. It stinks of rotten flesh and you want to move further into the lair. Which way do you want to go?"
>>>>>>> FrontEnd
                        },
                        new
                        {
                            RoomDescriptionID = 5,
<<<<<<< HEAD
                            Description = "DB says: This is room 5"
=======
                            Description = "5. This room seems empty and dark. There are writings on the wall and a little door for what you assume is for a dwarf-like creature. You check it out and conclude you can squeeze yourself through the door."
>>>>>>> FrontEnd
                        },
                        new
                        {
                            RoomDescriptionID = 6,
<<<<<<< HEAD
                            Description = "DB says: This is room 6"
=======
                            Description = "6. The whelps corpse has a weird smell to it. The room leads to another door. What is behind it?"
>>>>>>> FrontEnd
                        },
                        new
                        {
                            RoomDescriptionID = 7,
<<<<<<< HEAD
                            Description = "DB says: This is room 7"
=======
                            Description = "7. What is this? It looks like a cellar that hasn't been used for quite a while. A corpse is present behind the bars.The corpse has been there for a long time and has rotten down to mere bones.You stumble upon a key and a shield in the hands of the poor creature.Might be useful later."
>>>>>>> FrontEnd
                        },
                        new
                        {
                            RoomDescriptionID = 8,
<<<<<<< HEAD
                            Description = "DB says: This is room 8"
=======
                            Description = "8. This badly-lit corridor leads to a rusty door. What's behind it?"
>>>>>>> FrontEnd
                        },
                        new
                        {
                            RoomDescriptionID = 9,
<<<<<<< HEAD
                            Description = "DB says: This is room 9"
=======
                            Description = "9. The room is empty, but leads to another door."
>>>>>>> FrontEnd
                        },
                        new
                        {
                            RoomDescriptionID = 10,
<<<<<<< HEAD
                            Description = "DB says: This is room 10"
=======
                            Description = "10. It seems you've stumpled upon a dining room. Skeletons are still seated at the table. What the hell happened here? You gaze upon the table and see a key. Might be useful later."
>>>>>>> FrontEnd
                        },
                        new
                        {
                            RoomDescriptionID = 11,
<<<<<<< HEAD
                            Description = "DB says: This is room 11"
=======
                            Description = "11. Wait, a well? A rope is attached to it so i can climb down. A door is also present. Which way will you go? Either option seems dangerous. "
>>>>>>> FrontEnd
                        },
                        new
                        {
                            RoomDescriptionID = 12,
<<<<<<< HEAD
                            Description = "DB says: This is room 12"
=======
                            Description = "12. The room is lit by a mysterious item in the middle. This seems important for your journey."
>>>>>>> FrontEnd
                        },
                        new
                        {
                            RoomDescriptionID = 13,
<<<<<<< HEAD
                            Description = "DB says: This is room 13"
=======
                            Description = "13. The dead naked Gnoblin looks horrendous. That's a sight you don't want to see again."
>>>>>>> FrontEnd
                        },
                        new
                        {
                            RoomDescriptionID = 14,
<<<<<<< HEAD
                            Description = "DB says: This is room 14"
=======
                            Description = "14. Ew. The room is filled by a stench of rotten flesh. A dead soldier lies in the corner with a battleaxe in hand. It seems well-crafted."
>>>>>>> FrontEnd
                        },
                        new
                        {
                            RoomDescriptionID = 15,
<<<<<<< HEAD
                            Description = "DB says: This is room 15"
=======
                            Description = "15. The door locks as you enter the room. Something mysterious is happening."
>>>>>>> FrontEnd
                        },
                        new
                        {
                            RoomDescriptionID = 16,
<<<<<<< HEAD
                            Description = "DB says: This is room 16"
=======
                            Description = "16. The corridor is split between two ways. Which way do you take?"
>>>>>>> FrontEnd
                        },
                        new
                        {
                            RoomDescriptionID = 17,
<<<<<<< HEAD
                            Description = "DB says: This is room 17"
=======
                            Description = "17. The brute-gnoblin put up a good fight, but it is gone like the others. The room you entered is lit room with torches."
>>>>>>> FrontEnd
                        },
                        new
                        {
                            RoomDescriptionID = 18,
<<<<<<< HEAD
                            Description = "DB says: This is room 18"
=======
                            Description = "18. A door is present and you need a key. It might be somewhere else in the dungeon. You can sense an evil presence behind the door."
>>>>>>> FrontEnd
                        },
                        new
                        {
                            RoomDescriptionID = 19,
<<<<<<< HEAD
                            Description = "DB says: This is room 19"
=======
                            Description = "19. The Gnoblin king has been slayed. I can now retrieve the Sword of Destiny."
>>>>>>> FrontEnd
                        },
                        new
                        {
                            RoomDescriptionID = 20,
                            Description = "DB says: This is room 20"
                        });
                });

            modelBuilder.Entity("Backend_API.Models.Save", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

<<<<<<< HEAD
=======
                    b.Property<int?>("Armour_ID")
                        .HasColumnType("int");

                    b.Property<long?>("Health")
                        .HasColumnType("bigint");

>>>>>>> FrontEnd
                    b.Property<int>("RoomID")
                        .HasColumnType("int");

                    b.Property<string>("SaveName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(64)");

<<<<<<< HEAD
=======
                    b.Property<int?>("Weapon_ID")
                        .HasColumnType("int");

>>>>>>> FrontEnd
                    b.HasKey("ID");

                    b.HasIndex("Username");

                    b.HasIndex("SaveName", "Username")
                        .IsUnique();

                    b.ToTable("Saves");

                    b.HasData(
                        new
                        {
                            ID = 2,
<<<<<<< HEAD
                            RoomID = 1,
                            SaveName = "NewGame2",
                            Username = "Gamer1"
=======
                            Health = 10L,
                            RoomID = 0,
                            SaveName = "NewGame2",
                            Username = "gamer1"
>>>>>>> FrontEnd
                        },
                        new
                        {
                            ID = 1,
<<<<<<< HEAD
                            RoomID = 1,
                            SaveName = "NewGame1",
                            Username = "Gamer1"
=======
                            Health = 10L,
                            RoomID = 0,
                            SaveName = "NewGame1",
                            Username = "gamer1"
>>>>>>> FrontEnd
                        },
                        new
                        {
                            ID = 3,
<<<<<<< HEAD
                            RoomID = 1,
                            SaveName = "NewGame3",
                            Username = "Gamer1"
=======
                            Health = 10L,
                            RoomID = 0,
                            SaveName = "NewGame3",
                            Username = "gamer1"
>>>>>>> FrontEnd
                        },
                        new
                        {
                            ID = 4,
<<<<<<< HEAD
                            RoomID = 1,
                            SaveName = "NewGame4",
                            Username = "Gamer1"
=======
                            Health = 10L,
                            RoomID = 0,
                            SaveName = "NewGame4",
                            Username = "gamer1"
>>>>>>> FrontEnd
                        },
                        new
                        {
                            ID = 5,
<<<<<<< HEAD
                            RoomID = 1,
                            SaveName = "NewGame5",
                            Username = "Gamer1"
=======
                            Health = 10L,
                            RoomID = 0,
                            SaveName = "NewGame5",
                            Username = "gamer1"
>>>>>>> FrontEnd
                        });
                });

            modelBuilder.Entity("Backend_API.Models.User", b =>
                {
                    b.Property<string>("Username")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Username");

                    b.HasIndex("Username", "Password")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Username = "Gamer1",
<<<<<<< HEAD
                            Password = "$2a$11$kqFgv5.ZGVv7aoDyr6gW2uOiWKr7BxTxnKTwEffuRpUAsJwPHtThy"
=======
                            Password = "$2a$11$eBR2jvBORTwPn5i1fPnGn.8Z7zI4EwpPCbDul39D9ajjCthy/Rd32"
>>>>>>> FrontEnd
                        });
                });

            modelBuilder.Entity("Backend_API.Models.VisitedRooms", b =>
                {
                    b.Property<int>("SaveId")
                        .HasColumnType("int");

                    b.Property<long>("VistedRoomId")
                        .HasColumnType("bigint");

                    b.HasKey("SaveId", "VistedRoomId");

                    b.ToTable("VisitedRooms");
                });

<<<<<<< HEAD
=======
            modelBuilder.Entity("Backend_API.Models.Enemies_killed", b =>
                {
                    b.HasOne("Backend_API.Models.Save", "save")
                        .WithMany("Save_Enemies_killed")
                        .HasForeignKey("SaveID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("save");
                });

            modelBuilder.Entity("Backend_API.Models.Inventory_Items", b =>
                {
                    b.HasOne("Backend_API.Models.Save", "save")
                        .WithMany("Save_Inventory_Items")
                        .HasForeignKey("SaveID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("save");
                });

            modelBuilder.Entity("Backend_API.Models.Puzzles", b =>
                {
                    b.HasOne("Backend_API.Models.Save", "save")
                        .WithMany("Save_Puzzles")
                        .HasForeignKey("Save_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("save");
                });

>>>>>>> FrontEnd
            modelBuilder.Entity("Backend_API.Models.Save", b =>
                {
                    b.HasOne("Backend_API.Models.User", "User")
                        .WithMany("Saves")
                        .HasForeignKey("Username")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend_API.Models.VisitedRooms", b =>
                {
                    b.HasOne("Backend_API.Models.Save", "Save")
                        .WithMany("VisitedRooms")
                        .HasForeignKey("SaveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Save");
                });

            modelBuilder.Entity("Backend_API.Models.Save", b =>
                {
<<<<<<< HEAD
=======
                    b.Navigation("Save_Enemies_killed");

                    b.Navigation("Save_Inventory_Items");

                    b.Navigation("Save_Puzzles");

>>>>>>> FrontEnd
                    b.Navigation("VisitedRooms");
                });

            modelBuilder.Entity("Backend_API.Models.User", b =>
                {
                    b.Navigation("Saves");
                });
#pragma warning restore 612, 618
        }
    }
}
